### ISSUE TITLE
For problems: Switch off "last" marker

### ISSUE THREAD

**Issue by zenon** [deebloo/go-board#83]
Hi Danny, on Mastodon you said "Let me know if there is anything you would like to see added", and I'm not sure you knew what can of worms ... *grin*

So, I start small. Not by something to add, but by sth to remove, or rather be removable. Sometimes it is only the shape I want to show, then it is confusing that some stone is marked. So I'd like to be able to switch this off. I'd hope for an attribute like "noMarker".

(By the way, I use the go-board in my spare time, and don't have much. So, expect me to be lazy/restrained with follow ups, and all that, and please only respond if you really have time.)

Kind greetings! z.

**Comment by deebloo** [comment]
That should be pretty easy to implement. You are right a simple attribute would do it.

**Comment by deebloo** [comment]
done. add the "disablelastmarker" attribute to go-board
