### ISSUE TITLE
markers

### ISSUE THREAD

**Issue by zenon** [deebloo/go-board#84]
On the other hand, it is nice to be able to set custom markers onto stones.

I'd hope that there are neat unicode symbols, that are just shown in a layer above the stones. So the user chooses what mark to add to a stone like <go-stone color="black" slot="Q18" mark="+"></go-stone>

**Comment by deebloo** [comment]
Should be easy enough. If you add an element (any element) to the same slot as a stone it should appear on top. I could add a couple standard ones. (Like a green checkmark and red x)

**Comment by deebloo** [comment]
Markers have been added. Add go-stone-marker as a child of go-stone. You can put whatever you want inside. Later on I will add a handful of general use icons, but this is the foundation
```html
<go-board>
  <go-stone slot="Q4" color="black">
    <go-stone-marker>&check;</go-stone-marker>
  </go-stone>
</go-board>
```

**Comment by zenon** [comment]
Nice! Thank you!
