### ISSUE TITLE
board size

### ISSUE THREAD

**Issue by zenon** [deebloo/go-board#85]
It might be cool to change board size. I have no idea how difficult that is. Or if it is possible, how difficult it is to make it flexible.

Like <go-board size=9> for a 9x9 board.
Or even  <go-board sizeX=9 sizeY=13> for a 9x13 board.

Kind greetings!

**Comment by deebloo** [comment]
You can already change the board size! I don't think I have it documented so I will add it to the readme. I am also working on an option for focusing on on a particular section of the board.

**Comment by deebloo** [comment]
https://github.com/deebloo/go-board/blob/main/src/lib/board.ts#L194

**Comment by zenon** [comment]
Very nice!
The placement of star points is still non standard.
For some boards I found sth here. For other boards, don't know.
https://senseis.xmp.net/?5x5Board
https://senseis.xmp.net/?9x9Board
https://senseis.xmp.net/?11x11Board
https://senseis.xmp.net/?13x13Board
https://senseis.xmp.net/?15x15Board

**Comment by deebloo** [comment]
yeah that is why I didn't close this issue yet. need to figure out how to add them programmatically. At the moment it always puts them in the same pattern regardless of size

**Comment by deebloo** [comment]
@zenon what would you think if I gave a predefined set of board sizes instead of the current any size? then I could define how starpoints are defined
