### ISSUE TITLE
bug?: All mouse buttons place stones.

### ISSUE THREAD

**Issue by zenon** [deebloo/go-board#86]
I am not completely sure, but I think I don't like it.

My expectation as a use was: place with mouse left click.

If other mouse buttons shall work, they should do sth different. I mean, like: middle button always white, right button always black, or sth.

What do you mean?

**Comment by deebloo** [comment]
Oh that's a good point at the moment it is just a simple mouse down event listener. Not sure about other behaviors but I do agree only the left clinic should place the stone.

**Comment by deebloo** [comment]
fixed
