### ISSUE TITLE
loud thinking: getter, setter, or something?

### ISSUE THREAD

**Issue by zenon** [deebloo/go-board#87]
I'm not sure whether I need it. So see this as loud thinking only.

My current test use case for the board is visualisation for something I try out in Julia.
Starting there I see that we have a distributed logic: I'm building a representation of the board to generate a (currently random) move, and remove stones in case it killes something. That same killing/removing is done by your board.

Usually doing things twice, in parallel, with the expectation of consistency, is worth avoiding.
Your use case(s) seem to differ, so ignore if not needed :-)

However. To do this right, we need to have
A) either a way to set stones and remove stones, going around your logic,
B) or have a way to retrieve your board state, to verify whether your and my logic did the same, e.g. in tests.

I'm not sure whether it is sensible to do this "right" here. I sometimes tend to make problems more difficult, so feel free to ignore this.

Note that I even don't know yet how to use any of those possibilities for my Pluto notebooks ...

Kind greetings, z.

**Comment by deebloo** [comment]
So there are a few options. My original version of this was actually two components. The board component and a separate "game" component. It also should be pretty trivial to add a "novalidate" attribute to turn off the game logic.

**Comment by zenon** [comment]
Ah. Yes. This would also solve my suicidal issues :-)
In chinese rules, this is allowed, so I don't want a warning.

**Comment by deebloo** [comment]
added a novalidate attribute. It is in main and will go out with the next release
